# Generated by Django 4.0.3 on 2022-06-07 11:23

import MyKart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(max_length=30, unique=True)),
                ('lastname', models.CharField(max_length=30, unique=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('address', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20, validators=[MyKart.models.password_validator])),
                ('walletbalance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('BC', 'Body Care'), ('OC', 'Oral Care'), ('FI', 'Food Items'), ('DB', 'Drinks Beverages'), ('MH', 'Medicines Health'), ('EC', 'Electronics'), ('HA', 'Home Appliances'), ('CH', 'Clothing')], max_length=2)),
                ('quantity', models.IntegerField(default=1)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30)),
                ('product', models.ManyToManyField(to='MyKart.product')),
            ],
        ),
    ]
