# Generated by Django 4.0.3 on 2022-06-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
