# Generated by Django 4.0.3 on 2022-06-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKart', '0002_alter_customer_firstname_alter_customer_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='clothes.jpg', upload_to=''),
        ),
    ]
