# Generated by Django 4.0.3 on 2022-06-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKart', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Body Care', 'Body Care'), ('Electronics', 'Electronics'), ('Home Appliances', 'Home Appliances'), ('Clothing', 'Clothing')], max_length=20),
        ),
    ]
