# Generated by Django 4.0.3 on 2022-06-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('MyKart', '0004_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='Products.product'),
        ),
    ]
