# Generated by Django 4.0.3 on 2022-06-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_image'),
        ('MyKart', '0006_cart_quantity_cart_totalamt'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('totalamt', models.IntegerField(default=0)),
                ('product', models.ManyToManyField(to='Products.product')),
            ],
        ),
    ]
