# Generated by Django 4.0.3 on 2022-06-16 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKart', '0007_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 16)),
        ),
    ]
