# Generated by Django 4.0.3 on 2022-06-22 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKart', '0008_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 22)),
        ),
    ]
