# Generated by Django 4.0.3 on 2022-06-23 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKart', '0009_alter_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 23)),
        ),
    ]
