# Generated by Django 4.0.3 on 2022-07-01 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKart', '0010_orders_delivery_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 1)),
        ),
    ]
