# Generated by Django 4.0.3 on 2022-07-04 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKart', '0011_alter_orders_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='addedtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 4)),
        ),
    ]
