# Generated by Django 4.0.3 on 2022-06-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('Body Care', 'Body Care'), ('Electronics', 'Electronics'), ('Home Appliances', 'Home Appliances'), ('Clothing', 'Clothing')], max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='clothes.jpg', upload_to='')),
            ],
        ),
    ]
