# Generated by Django 4.0.3 on 2022-06-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='clothes.jpg', upload_to='images'),
        ),
    ]
