# Generated by Django 4.0.3 on 2022-07-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='keywords',
            field=models.TextField(default=0),
        ),
    ]
